---
version: "3"
services:
 devopsdb:
   image: arunkumarkoyyala/myapp:dbimage
   ports:
     - "3306:3306"

 application:
   image: arunkumarkoyyala/myapp:appimage
   ports:
     - "4321:8080"
   depends_on:
     - "devopsdb"
